name: yesod-example
version: "0.0.0"
tested-with: "GHC == 8.0.2, GHC == 8.2.2"

dependencies:
  - base
  - yesod-core

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  yesod-example:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rollbar-hs
      - text
      - wai-middleware-rollbar
      - warp
      - yesod-example
